FROM alpine:edge

RUN apk add --no-cache autoconf automake libtool gettext-dev gobject-introspection-dev g++ json-glib-dev  libgee-dev libxkbcommon-dev make vala extra-cmake-modules fcitx5-dev fcitx5-qt-dev qt6-qtbase-dev
